/**
 * Local feed adapter — reads JSON files generated by scripts/generate-feeds.mjs.
 * Gracefully skips if the file is missing or stale; callers log the warning.
 * @param {Object} data - Parsed JSON from data/feeds/{source}.json
 * @param {Array}  data.jobs - Array of raw job objects from the feed file
 * @returns {{ title, url, company, location }[]}
 */
export const localfeed = {
  parse: (data) => (data.jobs || []).map(j => ({
    title: j.title,
    url: j.url,
    company: j.company,
    location: j.location ?? null,
  })),
};
